network:
  version: 2
  ethernets:
    eth0:
      dhcp4: no
      addresses:
        - 192.168.1.5/24
      gateway4: 192.168.1.1
  wifis:
    wlan0:
      optional: true
      dhcp4: true
      access-points:
      # change this to your hotspots name
        "Hotspot Name":
          auth:
            key-management: "psk"
            # the hotspots password here
            password: "Hotspot Password"